name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: alantrrs/open_gns:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install test dependencies
        run: pip install pytest
      - name: Test
        run: python -m pytest
